package ui;

/*
 * DataViewUI.java
 *
 * Created on December 6, 2004, 10:12 AM
 */


import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.io.IOException;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.clustering.DataPoint;
import model.clustering.DataSet;
import model.clustering.DataSetIterator;
import persistence.DataSetDAO;
import persistence.DataSetDAOPlainFile;
import ptolemy.plot.Plot;
import util.distances.DistanceFunction;
import util.distances.EuclideanDistance;

/**
 *
 * @author jcsilva
 */
public class DataViewUI extends javax.swing.JFrame {

    /**
     * Creates new form DataViewUI
     */
    public DataViewUI(Hashtable data) {
        initComponents();
        initPlotter(data);
    }

    public DataViewUI(java.io.File file) {
        initComponents();
        System.out.println(file.getAbsolutePath());
        initPlotter(file);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void initPlotter(java.io.File file) {

        DistanceFunction distance = new EuclideanDistance();
        DataSetDAO nds = new DataSetDAOPlainFile(distance);


        DataSet ds = null;
        try {
            ds = nds.load(false, file.getAbsolutePath());
        } catch (IOException ex) {
            Logger.getLogger(DataViewUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        int dimension = 0;
        if (ds != null) {
            dimension = ds.getDim();
        }

        // Instantiate the two plots.
        Plot dataPlot = new Plot();
        System.out.println("new data plot");

        // Set the size of the toplevel window.
        //setSize(800, 350);

        //dataPlot.setSize(800, 300);
        dataPlot.setButtons(true);
        dataPlot.setTitle("Data Plot");
        //dataPlot.setYRange(-4, 4);
        //dataPlot.setXRange(0, 100);
        //dataPlot.setXLabel("X");
        //dataPlot.setYLabel("Y");
        //dataPlot.addYTick("-PI", -Math.PI);
        //dataPlot.addYTick("-PI/2", -Math.PI/2);
        //dataPlot.addYTick("0",0);
        //dataPlot.addYTick("PI/2", Math.PI/2);
        //dataPlot.addYTick("PI", Math.PI);
        dataPlot.setMarksStyle("dots");
        //dataPlot.setImpulses(true);

        // Call setConnected before reading in data.

        dataPlot.setConnected(false);


        boolean first = true;
        DataSetIterator dsi = ds.createIterator();
        int d = 0;

        for (int i = 0; i < ds.size(); i++) {
            //PATCH 20050111.01 Change
            // old line: DataPoint dp = dsi.currentItem();
            DataPoint dp = dsi.next();


            double x = dp.getValue(0);
            double y = 0; // TODO Choose dimensions to display
            if (dimension > 1) {   //This library accepts just 1 or 2-D! Other 
                y = dp.getValue(1);// dimensions will be ignored. 
            }
            dataPlot.addPoint(0, x, y, !first);
            System.out.println(dp);

            first = false;
            //PATCH 20050111.2 Delete
            //old line: dsi.next();
        }



        // Layout the two plots
        GridBagLayout gridbag = new GridBagLayout();
        GridBagConstraints c = new GridBagConstraints();
        getContentPane().setLayout(gridbag);

        // Handle the dataPlot
        c.gridx = 0;
        c.gridy = 0;
        c.gridwidth = 1;
        gridbag.setConstraints(dataPlot, c);
        getContentPane().add(dataPlot);



    }

    public void initPlotter(Hashtable data) {



        // Instantiate the two plots.
        Plot dataPlot = new Plot();
        // Set the size of the toplevel window.
        //setSize(800, 350);
        //dataPlot.setSize(800, 300);
        dataPlot.setButtons(true);
        dataPlot.setTitle("Data Plot");
        //dataPlot.setYRange(-4, 4);
        //dataPlot.setXRange(0, 100);
        //dataPlot.setXLabel("X");
        //dataPlot.setYLabel("Y");
        //dataPlot.addYTick("-PI", -Math.PI);
        //dataPlot.addYTick("-PI/2", -Math.PI/2);
        //dataPlot.addYTick("0",0);
        //dataPlot.addYTick("PI/2", Math.PI/2);
        //dataPlot.addYTick("PI", Math.PI);
        dataPlot.setMarksStyle("points");
        //dataPlot.setImpulses(true);
        // Call setConnected before reading in data.
        dataPlot.setConnected(true);
        boolean first = true;
        Enumeration keys = data.keys();
        while (keys.hasMoreElements()) {
            Long key = (Long) keys.nextElement();

            double x = key.doubleValue();

            double y = ((Double) data.get(key)).doubleValue();

            dataPlot.addPoint(0, x, y, !first);
            first = false;
        }
        // Layout the two plots
        GridBagLayout gridbag = new GridBagLayout();
        GridBagConstraints c = new GridBagConstraints();
        getContentPane().setLayout(gridbag);
        // Handle the dataPlot
        c.gridx = 0;
        c.gridy = 0;
        c.gridwidth = 1;
        gridbag.setConstraints(dataPlot, c);
        getContentPane().add(dataPlot);

    }

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        this.dispose();
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.io.File file = null;
        DataViewUI dataView = new DataViewUI(file);
        dataView.pack();
        dataView.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
//PATCHES 20050111 from .1 to .2